import * as NAMES_USER from '../../../utils/NAMES_CONST';

export const cardData = [
  {
    title: '人均播放视频数',
    graphName: '人均播放视频数',
    engTitle: 'Avg. Video Views Per User',
    id: '1',
    type: 'line',
    denominator: 'ply#type#dvc_cnt_3s_1d',
    molecular: 'ply#type#cnt_3s_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '平均视频播放数',
    graphName: '平均视频播放数',
    engTitle: 'Avg. Video Views Per Video',
    id: '2',
    type: 'line',
    denominator: 'ply#type#vdo_cnt_3s_1d',
    molecular: 'ply#type#cnt_3s_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均曝光数',
    graphName: '人均曝光数',
    engTitle: 'Avg. Video Exposures Per User',
    id: '3',
    type: 'line',
    denominator: 'exp#type#dvc_cnt_1d',
    molecular: 'exp#type#cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '有效人均播放时长(s)',
    graphName: '有效人均播放时长(s)',
    engTitle: 'Avg. Effective Watch Length Per User (ms)',
    id: '4',
    type: 'line',
    denominator: 'ply#type#dvc_cnt_3s_1d',
    molecular: 'ply_dur#type#3s_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均请求数',
    graphName: '人均请求数',
    engTitle: 'Avg. Video Request Per User',
    id: '5',
    type: 'line',
    denominator: 'exp_request_vivashow_dvc_cnt_1d',
    molecular: 'exp_request_vivashow_cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: false,
    onlyHotSelect: true,
  },
  {
    title: '人均点赞',
    graphName: '人均点赞',
    engTitle: 'Avg. Video Request Per User',
    id: '6',
    type: 'line',
    denominator: 'lk#type#dvc_cnt_1d',
    molecular: 'lk#type#cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均下载',
    graphName: '人均下载',
    engTitle: 'Avg. Video Download Per User',
    id: '7',
    type: 'line',
    denominator: 'dnld#type#dvc_cnt_1d',
    molecular: 'dnld#type#cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均评论',
    graphName: '人均评论',
    engTitle: 'Avg. Comment Per User',
    id: '8',
    type: 'line',
    denominator: 'cmnt#type#dvc_cnt_1d',
    molecular: 'cmnt#type#cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均转发',
    graphName: '人均转发',
    engTitle: 'Avg. Forward Per User',
    id: '9',
    type: 'line',
    denominator: 'fwd_wapp#type#dvc_cnt_1d',
    molecular: 'fwd_wapp#type#cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '人均搜索',
    graphName: '人均搜索',
    engTitle: '人均搜索',
    id: '10',
    type: 'line',
    denominator: 'srch_dvc_cnt_1d',
    molecular: 'srch_cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    onlyAllSelect: true,
  },
  {
    title: '人均举报',
    graphName: '人均举报',
    engTitle: '人均举报',
    id: '11',
    type: 'line',
    denominator: 'rpt_dvc_cnt_1d',
    molecular: 'rpt_cnt_1d',
    suffix: false,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    onlyAllSelect: true,
  },
  {
    title: 'ptr',
    graphName: 'ptr',
    engTitle: 'ptr',
    id: '12',
    type: 'line',
    denominator: 'exp#type#cnt_1d',
    molecular: 'ply#type#cnt_1d',
    suffix: true,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: 'ptr_3s',
    graphName: 'ptr_3s',
    engTitle: 'ptr_3s',
    id: '13',
    type: 'line',
    denominator: 'exp#type#cnt_1d',
    molecular: 'ply#type#cnt_3s_1d',
    suffix: true,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: 'dtr',
    graphName: 'dtr',
    engTitle: 'dtr',
    id: '14',
    type: 'line',
    denominator: 'exp#type#cnt_1d',
    molecular: 'dnld#type#cnt_1d',
    suffix: true,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: 'ltr',
    graphName: 'ltr',
    engTitle: 'ltr',
    id: '15',
    type: 'line',
    denominator: 'exp#type#cnt_1d',
    molecular: 'lk#type#cnt_1d',
    suffix: true,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'rpt_vid_itr_idx_1d',
    day: 'ds',
    product: 'product',
    hotSelect: true,
  },
  {
    title: '次留(%)',
    graphName: '次留(%)',
    engTitle: 'Retention For New User',
    id: '16',
    type: 'line',
    denominator: 'reg_num',
    molecular: 'stay_num',
    suffix: true,
    firstLevel: 'Dashboard',
    secondLevel: 'vid-dashboard',
    database: 'vivashow_user_stay',
    day: 'day',
    product: 'product',
  },
];

export const HOT_LIST = [
  { value: '_', title: 'all' },
  { value: '_vivashow_', title: 'vivashow' },
  { value: '_status_', title: 'status' },
  { value: '_search_', title: 'search' },
  { value: '_follow_', title: 'follow' },
];
export const CHART_LINE_NAMES = {
  new_device_total: NAMES_USER.NewUsers,
  login_total: NAMES_USER.RegisteredUsers,
  community_total: NAMES_USER.CommunityUsers,
  consume_total: NAMES_USER.Consumers,
  publish_total: NAMES_USER.Producer,
  tool_total: NAMES_USER.ToolUser,
  create_total: NAMES_USER.VideoMaker,
  like_in: NAMES_USER.LikeCount,
  forward_count: NAMES_USER.ShareCount,
  comment_count: NAMES_USER.CommentCount,
  download_count: NAMES_USER.CountOfDownload,
  likein_uv: NAMES_USER.UvOfLike,
  forward_uv: NAMES_USER.UvOfShare,
  comment_uv: NAMES_USER.UvOfComment,
  download_uv: NAMES_USER.UvOfDownload,
  play: NAMES_USER.ViewsRetention,
  community: NAMES_USER.CommunityRetention,
  play_in: NAMES_USER.InAppView,
  play_out: NAMES_USER.WebView,
  play_count: NAMES_USER.TotalView,
  publish_count: '发布视频个数',
  publish_uv: '发布人数(账号)',
  publish_dvc: '发布人数(设备)',
  exposure_count: '曝光次数',
  like_count: '点赞总数',
  like_uv: '点赞人数',
  play_uv: '播放人数',
  share_count: '转发次数',
  share_uv: '转发人数',
  exposure_uv: '曝光人数',
  follow_count: '关注次数',
  follow_uv: '关注人数',
  follow_count_uv: '人均关注数',
  follow_count_auid_uv: '人均被关注数',
  followed_auid_uv: '被关注人数',
  play_3s_count: '有效播放数',
  play_3s_uv: '有效播放人数',
  active_dvc_cnt_1d: '总体日活',
  app_active_dvc_cnt_1d: 'app客户端日活',
  community_dvc_cnt_1d: NAMES_USER.CommunityUsers,
  consume_dvc_cnt_1d: NAMES_USER.Consumers,
  exp_dvc_cnt_1d: '曝光用户',
  new_dvc_cnt_1d: '新增人数',
  tool_dvc_cnt_1d: NAMES_USER.ToolUser,
  ply_cnt_3s_1d: '有效播放量',
  ply_dvc_cnt_3s_1d: '有效播放人数',
};
