export const cardData = [
  {
    title: '音乐使用率',
    id: '1',
    type: 'line',
    ios_molecular: 'bgm_add_cnt',
    ios_denominator: 'bgm_enter_cnt',
    android_molecular: 'bgm_add_cnt',
    android_denominator: 'bgm_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '音乐搜索使用占比',
    id: '2',
    type: 'line',
    ios_molecular: 'bgm_search_clk_cnt',
    ios_denominator: 'bgm_enter_cnt',
    android_molecular: 'bgm_search_clk_cnt',
    android_denominator: 'bgm_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '音频使用率',
    id: '3',
    type: 'line',
    ios_molecular: 'sound_add_cnt',
    ios_denominator: 'sound_enter_cnt',
    android_molecular: 'sound_add_cnt',
    android_denominator: 'sound_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '音乐搜索有效率',
    id: '4',
    type: 'line',
    ios_molecular: 'bgm_add_search_cnt',
    ios_denominator: 'bgm_enter_cnt',
    android_molecular: 'bgm_add_search_cnt',
    android_denominator: 'bgm_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '滤镜使用率',
    id: '5',
    type: 'line',
    ios_molecular: 'ios_filter_clk_cnt',
    ios_denominator: 'add_filter_cnt',
    android_molecular: 'and_filter_clk_cnt',
    android_denominator: 'add_filter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '调色滤镜使用率',
    id: '81',
    type: 'line',
    ios_molecular: 'share_exp_colo_cnt',
    ios_denominator: 'colorfilter_add_cnt',
    android_molecular: 'share_exp_colo_cnt',
    android_denominator: 'colorfilter_add_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '特效滤镜使用率',
    id: '82',
    type: 'line',
    ios_molecular: 'share_exp_effe_cnt',
    ios_denominator: 'effectfilter_add_cnt',
    android_molecular: 'share_exp_effe_cnt',
    android_denominator: 'effectfilter_add_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '音乐&滤镜',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '主题需求度',
    id: '6',
    type: 'line',
    ios_molecular: 'preview_settheme_cnt',
    ios_denominator: 'preview_enter_cnt',
    android_molecular: 'preview_settheme_cnt',
    android_denominator: 'preview_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '主题',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '主题采纳率',
    id: '7',
    type: 'line',
    ios_molecular: 'exp_theme_cnt',
    ios_denominator: 'preview_settheme_cnt',
    android_molecular: 'exp_theme_cnt',
    android_denominator: 'preview_settheme_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '主题',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '字幕需求度',
    id: '8',
    type: 'line',
    ios_molecular: 'ios_title_clk_cnt',
    ios_denominator: 'gallery_enter_cnt',
    android_molecular: 'and_title_clk_cnt',
    android_denominator: 'gallery_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '字幕',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '字幕采纳率',
    id: '9',
    type: 'line',
    ios_molecular: 'exp_vdo_title_cnt',
    ios_denominator: 'ios_title_clk_cnt',
    android_molecular: 'exp_vdo_title_cnt',
    android_denominator: 'and_title_clk_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '字幕',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '贴纸需求度',
    id: '10',
    type: 'line',
    ios_molecular: 'ios_sticker_clk_cnt',
    ios_denominator: 'gallery_enter_cnt',
    android_molecular: 'and_sticker_clk_cnt',
    android_denominator: 'gallery_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '贴纸',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '贴纸采纳率',
    id: '11',
    type: 'line',
    ios_molecular: 'exp_vdo_sticker_cnt',
    ios_denominator: 'ios_sticker_clk_cnt',
    android_molecular: 'exp_vdo_sticker_cnt',
    android_denominator: 'and_sticker_clk_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '贴纸',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '特效采纳度',
    id: '12',
    type: 'line',
    ios_molecular: 'exp_fx_cnt',
    ios_denominator: 'ios_fx_clk_cnt',
    android_molecular: 'exp_fx_cnt',
    android_denominator: 'and_fx_clk_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '特效',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '特效使用率',
    id: '13',
    type: 'line',
    ios_molecular: 'exp_fx_cnt',
    ios_denominator: 'add_fx_cnt',
    android_molecular: 'exp_fx_cnt',
    android_denominator: 'add_fx_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '特效',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '特效需求度',
    id: '14',
    type: 'line',
    ios_molecular: 'ios_fx_clk_cnt',
    ios_denominator: 'gallery_enter_cnt',
    android_molecular: 'and_fx_clk_cnt',
    android_denominator: 'gallery_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '特效',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '转场需求度',
    id: '15',
    type: 'line',
    ios_molecular: 'clk_tstion_cnt',
    ios_denominator: 'preview_enter_cnt',
    android_molecular: 'clk_tstion_cnt',
    android_denominator: 'preview_enter_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '转场',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '转场使用率',
    id: '16',
    type: 'line',
    ios_molecular: 'ios_exp_tstion_cnt',
    ios_denominator: 'add_tstion_cnt',
    android_molecular: 'and_exp_tstion_cnt',
    android_denominator: 'add_tstion_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '转场',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
  {
    title: '转场采纳率',
    id: '17',
    type: 'line',
    ios_molecular: 'ios_exp_tstion_cnt',
    ios_denominator: 'clk_tstion_cnt',
    android_molecular: 'and_exp_tstion_cnt',
    android_denominator: 'clk_tstion_cnt',
    suffix: true,
    firstLevel: '素材关键指标',
    secondLevel: '小影素材指标',
    thirdLevel: '转场',
    database: 'ads_viva_log_material_pojcnt_1d',
    day: 'ds',
    product: 'product',
  },
];

export const TABLE_INFO = {
  columns: [
    { dataIndex: 'category', title: '类目', key: 'category' },
    { dataIndex: 'add_material_cnt', title: '添加素材工程数', key: 'add_material_cnt' },
    { dataIndex: 'material_exp_cnt', title: '带素材保存/导出工程数', key: 'material_exp_cnt' },
    {
      dataIndex: 'material_exp_cnt/add_material_cnt',
      title: '素材使用率(%)',
      key: 'material_exp_cnt/add_material_cnt',
    },
  ],
  exportDetailColumns: [
    { dataIndex: 'country', title: '地区', key: 'country' },
    { dataIndex: 'new_user', title: '用户', key: 'new_user' },
    { dataIndex: 'category', title: '类目', key: 'category' },
    { dataIndex: 'ttid', title: 'ttid', key: 'ttid' },
    { dataIndex: 'add_material_cnt', title: '添加素材工程数', key: 'add_material_cnt' },
    { dataIndex: 'material_exp_cnt', title: '带素材保存/导出工程数', key: 'material_exp_cnt' },
    {
      dataIndex: 'material_exp_cnt/add_material_cnt',
      title: '素材使用率(%)',
      key: 'material_exp_cnt/add_material_cnt',
    },
  ],
  database: 'ads_viva_log_material_ctgy_cnt_1d',
  groupBy: ['category'],
  orderBy: ['add_material_cnt desc'],
  product: 'product',
  day: 'ds',
  sort: 'add_material_cnt',
};

export const TITLE_INFO = {
  columns: [
    {
      dataIndex: 'category',
      title: '类目',
      key: 'category',
    },
    { dataIndex: 'add_title_cnt', title: '添加素材工程数', key: 'add_title_cnt' },
    { dataIndex: 'exp_vdo_title_cnt', title: '带素材保存/导出工程数', key: 'exp_vdo_title_cnt' },
    { dataIndex: 'exp_vdo_title_cnt/add_title_cnt', title: '素材使用率(%)', key: 'exp_vdo_title_cnt/add_title_cnt' },
  ],
  database: 'ads_viva_log_material_ctgy_cnt_1d',
  groupBy: ['category'],
  orderBy: ['add_title_cnt desc'],
  product: 'product',
  day: 'ds',
  sort: 'add_title_cnt',
};
export const STICKER_INFO = {
  columns: [
    {
      dataIndex: 'category',
      title: '类目',
      key: 'category',
    },
    { dataIndex: 'add_sticker_cnt', title: '添加素材工程数', key: 'add_sticker_cnt' },
    { dataIndex: 'exp_vdo_sticker_cnt', title: '带素材保存/导出工程数', key: 'exp_vdo_sticker_cnt' },
    {
      dataIndex: 'exp_vdo_sticker_cnt/add_sticker_cnt',
      title: '素材使用率(%)',
      key: 'exp_vdo_sticker_cnt/add_sticker_cnt',
    },
  ],
  database: 'ads_viva_log_material_ctgy_cnt_1d',
  groupBy: ['category'],
  orderBy: ['add_sticker_cnt desc'],
  product: 'product',
  day: 'ds',
  sort: 'add_sticker_cnt',
};
