export const menus = [
  // {
  //   id: '1',
  //   router: '/gh/dashboard',
  //   title: 'Dashboard',
  //   pTitle: 'Home',
  // },
  // {
  //   id: '2',
  //   router: '/gh/template-inline',
  //   title: '模版实时数据',
  //   pTitle: 'Home',
  // },
  // {
  //   id: '3',
  //   router: '/gh/okr',
  //   title: 'OKR',
  //   pTitle: 'Home',
  // },
  //
  // {
  //   id: '51',
  //   router: '/gh/analytics/retention',
  //   title: '留存',
  //   pTitle: '概览分析',
  // },
  // {
  //   id: '52',
  //   router: '/gh/analytics/active-device',
  //   title: '活跃设备',
  //   pTitle: '概览分析',
  // },
  // {
  //   id: '53',
  //   router: '/gh/analytics/active-analytics',
  //   title: '活跃设备',
  //   pTitle: '概览分析',
  // },
  {
    id: '1',
    router: null,
    title: '整体概览',
    pTitle: 'home',
    pTid: null,
    children: [
      {
        id: '11',
        router: '/gh/home/viva',
        title: 'viva整体概览',
        pTitle: 'home',
        pTid: '1',
      },
      {
        id: '12',
        router: '/gh/home/vivacut',
        title: 'vivacut整体概览',
        pTitle: 'home',
        pTid: '1',
      },
      {
        id: '13',
        router: '/gh/home/sp',
        title: 'slideplus整体概览',
        pTitle: 'home',
        pTid: '1',
      },
      {
        id: '14',
        router: '/gh/home/vivamini',
        title: '趣影整体概览',
        pTitle: 'home',
        pTid: '1',
      },
    ],
  },
  {
    id: '2',
    router: '/gh/1',
    title: 'dashboard',
    pTitle: 'home',
    pTid: null,
  },
  {
    id: '3',
    router: '/gh/config',
    title: '配置',
    pTitle: 'home',
    pTid: null,
  },
  {
    id: '4',
    router: '/gh/material/viva',
    title: '小影素材指标',
    pTitle: '素材关键指标',
  },
  {
    id: '5',
    router: null,
    title: 'Dashboard',
    pTid: null,
    children: [
      {
        id: '51',
        router: '/gh/dashboard/vid',
        title: 'vid-dashboard',
        pTitle: 'Dashboard',
        pTid: '5',
      },
      {
        id: '52',
        router: '/gh/dashboard/viva',
        title: 'viva-dashboard',
        pTitle: 'Dashboard',
        pTid: '5',
      },
      {
        id: '53',
        router: '/gh/dashboard/vivamini',
        title: 'Dashboard',
        pTitle: '用户分析',
        pTid: '5',
      },
    ],
  },
  {
    id: '6',
    router: null,
    title: '用户分析',
    pTid: null,
    children: [
      {
        id: '61',
        router: '/gh/vid/user-analytics/creator',
        title: 'vid-创作用户',
        pTitle: '用户分析',
        pTid: '6',
      },
    ],
  },
  {
    id: '7',
    router: null,
    title: '自定义事件',
    pTid: null,
    children: [
      {
        id: '71',
        router: '/gh/event/viva',
        title: 'viva-自定义事件',
        pTitle: '自定义事件',
        pTid: '7',
      },
      {
        id: '72',
        router: '/gh/event/vivacut',
        title: 'vivacut-自定义事件',
        pTitle: '自定义事件',
        pTid: '7',
      },
      {
        id: '73',
        router: '/gh/event/tempo',
        title: 'tempo-自定义事件',
        pTitle: '自定义事件',
        pTid: '7',
      },
      {
        id: '74',
        router: '/gh/event/vivamini',
        title: '事件查询',
        pTitle: '行为分析',
        pTid: '7',
      },
    ],
  },
  {
    id: '8',
    router: '/gh/okr-china',
    title: '国内OKR',
    pTitle: 'Home',
  },
  {
    id: '9',
    router: null,
    title: '视频分析',
    pTid: null,
    children: [
      {
        id: '91',
        router: '/gh/video/tag-video',
        title: '标签视频',
        pTitle: '视频分析',
        pTid: '9',
      },
      {
        id: '92',
        router: '/gh/video/hot-video',
        title: '热门视频质量统计',
        pTitle: '视频分析',
        pTid: '9',
      },
      {
        id: '93',
        router: '/gh/video/tag-hot',
        title: '标签热门数据',
        pTitle: '视频分析',
        pTid: '9',
      },
    ],
  },
  {
    id: '10',
    router: null,
    title: '投放分析',
    pTid: null,
    children: [
      {
        id: '93',
        router: '/gh/source-analytics/viva',
        title: '来源分析',
        pTitle: '投放分析',
        pTid: '10',
      },
    ],
  },
];
