/*
 * @Description:
 * @Author: ssssslf
 * @Date: 2020-03-27 11:08:23
 * @LastEditTime: 2020-03-30 17:43:54
 * @LastEditors: ssssslf
 */
export const cardData = [
  {
    title: 'Push_Show_Rate_of_New Device(%)',
    graphName: 'Push_Show_Rate_of_New Device(%)',
    id: '1',
    type: 'line',
    molecular: 'shows_new_usr_cnt',
    denominator: 'new_usr_cnt',
    suffix: true,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '%',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'Push_Show_Count_Per_New_Device',
    graphName: 'Push_Show_Count_Per_New_Device',
    id: '2',
    type: 'line',
    molecular: 'new_usr_avg_shows_cnt*shows_new_usr_cnt',
    denominator: 'shows_new_usr_cnt',
    suffix: false,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '',
    otherWhere: 'and tag = \'all\'',
    molecularName: 'shows_cnt',
  },
  {
    title: 'Push_Receive_Rate_of_New_Device(%)',
    graphName: 'Push_Receive_Rate_of_New_Device(%)',
    id: '3',
    type: 'line',
    molecular: 'recive_new_usr_cnt',
    denominator: 'new_usr_cnt',
    suffix: true,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '%',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'Push_Receive_Count_Per_New_Device',
    graphName: 'Push_Receive_Count_Per_New_Device',
    id: '4',
    type: 'line',
    molecular: 'new_usr_avg_recive_cnt*recive_new_usr_cnt',
    denominator: 'recive_new_usr_cnt',
    suffix: false,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '',
    otherWhere: 'and tag = \'all\'',
    molecularName: 'recive_cnt',
  },
  {
    title: 'Total_Receive_Count',
    graphName: 'Total_Receive_Count',
    id: '5',
    type: 'line',
    molecular: 'recive',
    suffix: false,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'Total_Show_Count shows',
    graphName: 'Total_Show_Count shows',
    id: '6',
    type: 'line',
    molecular: 'shows',
    suffix: false,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'Total_Click_Count click',
    graphName: 'Total_Click_Count click',
    id: '7',
    type: 'line',
    molecular: 'click',
    suffix: false,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'click/receive(%)',
    graphName: 'click/receive(%)',
    id: '8',
    type: 'line',
    molecular: 'click',
    denominator: 'recive',
    suffix: true,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '%',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'Not_Receive_Push_Rate(%)',
    graphName: 'Not_Receive_Push_Rate(%)',
    id: '9',
    type: 'line',
    molecular: 'no_recive_usr_cnt',
    denominator: 'acti_usr_cnt_7d',
    suffix: true,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '%',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: 'First_Open_App_via_Push_Rate(%)',
    graphName: 'First_Open_App_via_Push_Rate(%)',
    id: '10',
    type: 'line',
    molecular: 'push_cnt',
    denominator: 'acti_usr_cnt',
    suffix: true,
    database: 'mb_vid_push_dashboard',
    day: 'ds',
    unit: '%',
    otherWhere: 'and tag = \'all\'',
  },
  {
    title: '收到push设备数',
    graphName: '收到push设备数',
    id: '11',
    type: 'line',
    molecular: 'push_receive_dvc_cnt',
    suffix: false,
    database: 'vivashow_push_data',
    day: 'ds',
    unit: '',
    otherWhere: '',
  },
  {
    title: '点击push设备占比(%)',
    graphName: '点击push设备占比(%)',
    id: '12',
    type: 'line',
    molecular: 'push_click_dvc_cnt',
    denominator: 'push_receive_dvc_cnt',
    suffix: true,
    database: 'vivashow_push_data',
    day: 'ds',
    unit: '',
    otherWhere: '',
  },
];
