export const products = {
  install: {
    ds: 'bizdate',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'product',
      values: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
  sale: {
    ds: 'data_time',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'app_product',
      values: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
  cost: {
    ds: 'ds',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'product_id',
      values: {
        2: '2',
        3: '3',
        6: '6',
        10: '10',
        15: '15',
        16: '16',
        33: '33',
        35: '35',
      },
      mapping: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
};

export const productMapping = {
  2: 'viva',
  3: 'sp',
  6: 'vid',
  10: 'tempo',
  15: 'vivacut',
  16: 'vivamini',
  33: 'picsfox',
  35: 'facee',
  18: 'VMix',
  36: 'Glitch',
  // 38: '小影马甲包',
  44: '小影印度马甲包',
  43: 'GoCut',
  42: 'mast',
  41: 'StoryBuff',
  39: 'Veffecto',
  51: 'multirecorder',
  50: 'beatstarr',
};

export const productTypeMapping = {
  2: 'viva',
  3: 'sp',
  6: 'vid',
  10: 'tempo',
  15: 'vivacut',
  16: 'vivamini',
  33: 'picsfox',
  35: 'facee',
  18: 'vmix',
  36: 'glitchfx',
  // 38: '小影马甲包',
  44: 'vivavideoindia',
  43: 'gocut',
  42: 'mast',
  41: 'storybuff',
  39: 'veffecto',
  51: 'multirecorder',
  50: 'beatstarr',
};

export const typeProductMapping = {
  viva: '2',
  sp: '3',
  vid: '6',
  tempo: '10',
  vivacut: '15',
  vivamini: '16',
  vmix: '18',
  picsfox: '33',
  facee: '35',
  glitchfx: '36',
  veffecto: '39',
  storybuff: '41',
  mast: '42',
  gocut: '43',
  vivavideoindia: '44',
  beatstarr: '50',
  multirecorder: '51',
};
