export const AbsCardData = [
  {
    title: '活跃设备数',
    graphName: '活跃设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'active_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '活跃次数',
    graphName: '活跃次数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'active_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '列表设备数',
    graphName: '列表设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'exp_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '列表次数',
    graphName: '列表次数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'exp_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '曝光设备数',
    graphName: '活跃设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'exp_dvc_cnt_all',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '曝光次数',
    graphName: '活跃设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'exp_cnt_all',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '预览设备数',
    graphName: '预览设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'pre_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '预览次数',
    graphName: '预览次数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'pre_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '导出设备数',
    graphName: '导出设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'export_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '导出次数',
    graphName: '导出次数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'export_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '分享设备数',
    graphName: '分享设备数',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'shr_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: false,
  },
  {
    title: '分享次数',
    graphName: '分享设备量',
    id: '1',
    type: 'line',
    noDenominator: true,
    molecular: 'shr_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '人均制作视频量',
    graphName: '人均制作视频量',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'export_cnt',
    denominator: 'exp_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '人均分享视频量',
    graphName: '人均分享视频量',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'shr_cnt',
    denominator: 'shr_dvc_cnt',
    suffix: false,
    day: 'ds',
    typeSelect: true,
  },
];

export const PerCardData = [
  {
    title: '列表设备占比',
    graphName: '列表设备占比',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'exp_dvc_cnt',
    denominator: 'active_dvc_cnt_02',
    suffix: true,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '预览设备占比',
    graphName: '预览设备占比',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'pre_dvc_cnt',
    denominator: 'active_dvc_cnt_02',
    suffix: true,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '导出设备占比',
    graphName: '导出设备占比',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'export_dvc_cnt',
    denominator: 'active_dvc_cnt_02',
    suffix: true,
    day: 'ds',
    typeSelect: true,
  },
  {
    title: '分享设备占比',
    graphName: '分享设备占比',
    id: '1',
    type: 'line',
    noDenominator: false,
    molecular: 'shr_dvc_cnt',
    denominator: 'active_dvc_cnt_02',
    suffix: true,
    day: 'ds',
    typeSelect: true,
  },
];
