/* eslint-disable max-len */
export const countryList = {
  1: '全部',
  2: '中美日韩台泰',
  3: '第二梯度',
  4: '第三梯度',
};

export const COUNTRY_LIST = {
  1: ['中国', '美国', '日本', '韩国', '台湾', '泰国', '巴西', '印度尼西亚'],
  2: ['中国', '美国', '日本', '韩国', '台湾', '泰国'],
  3: [
    '马来西亚',
    '俄罗斯',
    '英国',
    '西班牙',
    '德国',
    '沙特阿拉伯',
    '澳大利亚',
    '法国',
    '加拿大',
    '香港',
    '意大利',
    '新加坡',
    '阿联酋',
    '以色列',
    '阿根廷',
    '瑞士',
    '新西兰',
    '科威特',
    '智利',
    '奥地利',
    '荷兰',
    '瑞典',
    '阿曼',
    '比利时',
    '芬兰',
    '罗马尼亚',
    '波兰',
    '挪威',
    '卡塔尔',
    '爱尔兰',
    '捷克共和国',
    '哥斯达黎加',
    '巴拿马',
    '葡萄牙',
    '丹麦',
    '希腊',
    '澳门',
    '匈牙利',
    '斯洛伐克',
    '巴林',
    '乌拉圭',
    '波多黎各',
    '立陶宛',
    '克罗地亚',
    '拉脱维亚',
    '塞浦路斯',
    '斯洛文尼亚',
    '特立尼达和多巴哥',
    '爱沙尼亚',
    '巴哈马',
    '卢森堡',
    '毛里求斯',
    '马耳他',
    '文莱',
    '冰岛',
    '安提瓜和巴布达',
    '巴巴多斯',
    '阿鲁巴',
    '圣基茨和尼维斯',
    '帕劳',
    '塞舌尔',
    '格林纳达',
    '圣卢西亚',
  ],
};

export const COUNTRY_NAME_COMMON_LIST = [
  {
    country_code: '全部',
    country_name: '全部',
  },
  {
    country_code: '重点地区',
    country_name: '重点地区',
  },
  { country_code: '中国\', \'美国\', \'日本\', \'韩国\', \'台湾\', \'泰国', country_name: '中美日韩台泰' },
  {
    country_code: '第二梯度',
    country_name: '第二梯度',
  },
  {
    country_code: '第三梯度',
    country_name: '第三梯度',
  },
  {
    country_code:
      '法国\', \'荷兰\', \'比利时\', \'卢森堡\', \'瑞士\', \'列支敦士登\', \'奥地利\', \'摩纳哥\', \'德国\', \'波兰\', \'匈牙利\', \'斯洛伐克\', \'捷克\', \'保加利亚\', \'罗马尼亚\', \'摩尔多瓦\', \'俄罗斯\', \'英国\', \'丹麦\', \'挪威\', \'冰岛\', \'芬兰\', \'瑞典\', \'立陶宛\', \'拉脱维亚\', \'爱沙尼亚\', \'爱尔兰\', \'法罗群岛\', \'斯瓦尔巴\', \'葡萄牙\', \'西班牙\', \'希腊\', \'意大利\', \'梵蒂冈\', \'安道尔\', \'北马其顿\', \'圣马力诺\', \'马耳他\', \'斯洛文尼亚\', \'克罗地亚\', \'波黑\', \'黑山\', \'塞尔维亚\', \'科索沃\', \'阿尔巴尼亚\', \'马耳他骑士团\', \'新西兰\', \'澳大利亚\', \'美国\', \'加拿大',
    country_name: '欧美',
  },
  { country_code: '巴西\', \'墨西哥\', \'阿根廷\', \'智利', country_name: '拉美' },
  {
    country_code: '印度尼西亚\', \'马来西亚\', \'菲律宾\', \'泰国\', \'新加坡\', \'文莱\', \'柬埔寨\', \'老挝\', \'缅甸\', \'越南',
    country_name: '东南亚十国',
  },
  { country_code: '俄罗斯\', \'白俄罗斯\', \'哈萨克斯坦\', \'吉尔吉斯斯坦\', \'乌克兰', country_name: '俄语区' },
];

const sorter = () => function sort(a, b) {
  return a[this.key] - b[this.key];
};

export const tagColors = ['magenta', 'red', 'volcano', 'orange', 'gold'];

export const dateTags = [
  {
    key: '7',
    value: 7,
    title: '最近7天',
  },
  {
    key: '30',
    value: 30,
    title: '最近30天',
  },
  {
    key: '60',
    value: 60,
    title: '最近60天',
  },
  {
    key: '90',
    value: 90,
    title: '最近90天',
  },
];

export const COLUMNS = [
  {
    dataIndex: 'new_dvc_cnt',
    key: 'new_dvc_cnt',
    title: 'new_dvc_cnt',
    extendInfo: '总新增',
    sorter: sorter(),
  },
  {
    dataIndex: 'o_new_dvc_cnt',
    key: 'o_new_dvc_cnt',
    title: 'o_new_dvc_cnt',
    extendInfo: '自然新增',
    sorter: sorter(),
  },
  {
    dataIndex: 'p_new_dvc_cnt',
    key: 'p_new_dvc_cnt',
    title: 'p_new_dvc_cnt',
    extendInfo: '投放新增',
    sorter: sorter(),
  },
  {
    dataIndex: 'sale_amt',
    key: 'sale_amt',
    title: 'sale_amt',
    extendInfo: '总销售额(美元)',
    sorter: sorter(),
  },
  {
    dataIndex: 'o_sale_amt',
    key: 'o_sale_amt',
    title: 'o_sale_amt',
    extendInfo: '自然销售额(美元)',
    sorter: sorter(),
  },
  {
    dataIndex: 'p_sale_amt',
    key: 'p_sale_amt',
    title: 'p_sale_amt',
    extendInfo: '投放销售额(美元)',
    sorter: sorter(),
  },
];
const width = 120;
export const TOTALCOLUMNS = [
  {
    dataIndex: 'INSTALL',
    key: 'INSTALL',
    title: 'INSTALL',
    extendInfo: '新增用户',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'dau',
    key: 'dau',
    title: 'dau',
    extendInfo: '日活跃用户',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'cost',
    key: 'cost',
    title: 'cost',
    extendInfo: '消耗',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'revenue',
    key: 'revenue',
    title: 'revenue',
    extendInfo: '实时收入(美元)',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'arpdau',
    key: 'arpdau',
    title: 'arpdau',
    extendInfo: '实时收入/日活用户',
    width,
    sorter: sorter(),
    // render: (text, record) => record.revenue / record.dau,
  },
];

export const SALECOLUMNS = [
  // {
  //   dataIndex: 'year_free',
  //   key: 'year_free',
  //   title: 'year_free',
  //   extendInfo: '年试用成功订单',
  //   width,
  //   sorter: sorter(),
  // },
  // {
  //   dataIndex: 'month_free',
  //   key: 'month_free',
  //   title: 'month_free',
  //   extendInfo: '月试用成功订单',
  //   width,
  //   sorter: sorter(),
  // },
  {
    dataIndex: 'refund_amt',
    key: 'refund_amt',
    title: 'refund_amt',
    extendInfo: '退款金额(美元)',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'year_new_purchase',
    key: 'year_new_purchase',
    title: 'year_new_purchase',
    extendInfo: '年首购订单',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'month_new_purchase',
    key: 'month_new_purchase',
    title: 'month_new_purchase',
    extendInfo: '月首购订单',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'year_renew_purchase',
    key: 'year_renew_purchase',
    title: 'year_renew_purchase',
    extendInfo: '年续购订单',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'month_renew_purchase',
    key: 'month_renew_purchase',
    title: 'month_renew_purchase',
    extendInfo: '月续购订单',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'other_purchase',
    key: 'other_purchase',
    title: 'other_purchase',
    extendInfo: '其他包订单',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'year_revenue',
    key: 'year_revenue',
    title: 'year_revenue',
    extendInfo: '年包收入(美元)',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'month_revenue',
    key: 'month_revenue',
    title: 'month_revenue',
    extendInfo: '月包收入(美元)',
    width,
    sorter: sorter(),
  },
  {
    dataIndex: 'other_revenue',
    key: 'other_revenue',
    title: 'other_revenue',
    extendInfo: '其他包收入(美元)',
    width,
    sorter: sorter(),
  },
];
