/*
 * @Description:
 * @Author: ssssslf
 * @Date: 2020-08-15 19:27:38
 * @LastEditTime: 2020-12-21 18:58:47
 * @LastEditors: dongqi.zhao
 */

export const initData = [
  {
    fields: 'home_view_dvc_cnt',
    title: '展示量',
  },
  {
    fields: 'template_make_dvc_cnt',
    title: '制作量',
  },
  {
    fields: 'share_dvc_cnt',
    title: '分享量',
  },
  {
    fields: 'pay_dvc_cnt/home_view_dvc_cnt',
    title: '平均模版付费率',
  },
  {
    fields: 'template_make_dvc_cnt/home_view_dvc_cnt',
    title: '生成中模版制作率',
  },
  {
    fields: 'share_dvc_cnt/template_make_dvc_cnt',
    title: '视频平均分享率',
  },
];

export const columns = {
  16: [
    { dataIndex: 'tt_name', title: '模版名称' },
    { dataIndex: 'ttid', title: 'ttid' },
    { dataIndex: 'home_view_dvc_cnt', title: '模版展示-首页展示' },
    { dataIndex: 'home_click_dvc_cnt', title: '模板首页-点击' },
    { dataIndex: 'home_click_dvc_cnt/home_view_dvc_cnt', title: '首页点击率(%)' },
    { dataIndex: 'template_view_dvc_cnt', title: '模版页展示量' },
    { dataIndex: 'make_button_click_dvc_cnt', title: '模板页制作button点击量' },
    { dataIndex: 'make_button_click_dvc_cnt/template_view_dvc_cnt', title: '模板页点击率(%)' },
    { dataIndex: 'template_make_dvc_cnt', title: '模版页制作量' },
    { dataIndex: 'template_make_dvc_cnt/template_view_dvc_cnt', title: '模版页制作率(%)' },
    { dataIndex: 'share_dvc_cnt', title: '视频分享量' },
    { dataIndex: 'share_dvc_cnt/template_make_dvc_cnt', title: '视频分享率(%)' },
    { dataIndex: 'template_make_dvc_cnt/home_view_dvc_cnt', title: '总完成率(%)' },
    { dataIndex: 'total_make_dvc_cnt', title: '总制作量' },
    { dataIndex: 'make_fail_dvc_cnt', title: '模版制作失败量' },
    { dataIndex: 'make_fail_dvc_cnt/template_make_dvc_cnt', title: '模版制作失败率(%)' },
    { dataIndex: 'pay_dvc_cnt', title: '模版付费数' },
    { dataIndex: 'pay_dvc_cnt/template_view_dvc_cnt', title: '模版付费率(%)' },
    { dataIndex: 'coin_60_dvc_cnt', title: '按60金币购买' },
    { dataIndex: 'coin_200_dvc_cnt', title: '按200金币购买' },
    { dataIndex: 'month_buy_dvc_cnt', title: '按月度会员购买' },
    { dataIndex: 'year_buy_dvc_cnt', title: '按年度会员购买' },
  ],
  35: {
    1: [
      { dataIndex: 'tt_name', title: '模版名称' },
      { dataIndex: 'ttid', title: 'ttid' },
      { dataIndex: 'home_view_dvc_cnt', title: '模版展示-首页展示' },
      { dataIndex: 'home_click_dvc_cnt', title: '模板首页-点击' },
      { dataIndex: 'home_click_dvc_cnt/home_view_dvc_cnt', title: '首页点击率(%)' },
      { dataIndex: 'template_view_dvc_cnt', title: '模版相册页展示量uv' },
      { dataIndex: 'make_button_click_dvc_cnt', title: '模板制作量uv' },
      { dataIndex: 'make_button_click_dvc_cnt/template_view_dvc_cnt', title: '用户制作率(%)' },
      { dataIndex: 'save_dvc_cnt', title: '模板保存uv' },
      { dataIndex: 'save_dvc_cnt/make_button_click_dvc_cnt', title: '保存率' },
      { dataIndex: 'save_dvc_cnt/home_view_dvc_cnt', title: '总完成率' },
      { dataIndex: 'share_dvc_cnt', title: '分享量' },
      { dataIndex: 'share_dvc_cnt/make_button_click_dvc_cnt', title: '分享率(%)' },
      { dataIndex: 'make_fail_dvc_cnt', title: '模版制作失败量' },
      { dataIndex: 'make_fail_dvc_cnt/make_button_click_dvc_cnt', title: 'uv模板制作失败率(%)' },
      { dataIndex: 'make_fail_cnt/total_make_cnt', title: 'pv模板制作失败率(%)' },
      { dataIndex: 'home_click_cnt', title: '模板首页-点击/pv' },
      { dataIndex: 'template_make_dvc_cnt', title: '素材编辑/uv' },
      { dataIndex: 'save_cnt', title: '模版保存/pv' },
      { dataIndex: 'share_cnt', title: '模版分享/pv' },
      { dataIndex: 'home_click_cnt/home_click_dvc_cnt', title: '人均模版使用次数' },
      { dataIndex: 'save_cnt/save_dvc_cnt', title: '人均模版保存次数' },
      { dataIndex: 'share_cnt/share_dvc_cnt', title: '人均模版分享次数' },
      { dataIndex: 'total_make_cnt', title: '总制作量（pv）' },
    ],
    2: [
      { dataIndex: 'tt_name', title: '模版名称' },
      { dataIndex: 'ttid', title: 'ttid' },
      { dataIndex: 'home_view_dvc_cnt', title: '模版展示-首页展示' },
      { dataIndex: 'home_click_dvc_cnt', title: '模板首页-点击' },
      { dataIndex: 'home_click_dvc_cnt/home_view_dvc_cnt', title: '首页点击率(%)' },
      { dataIndex: 'template_view_dvc_cnt', title: '模版相册页展示量uv' },
      { dataIndex: 'make_button_click_dvc_cnt', title: '模板制作量uv' },
      { dataIndex: 'make_button_click_dvc_cnt/template_view_dvc_cnt', title: '用户制作率(%)' },
      { dataIndex: 'save_dvc_cnt', title: '模板保存uv' },
      { dataIndex: 'save_dvc_cnt/make_button_click_dvc_cnt', title: '保存率' },
      { dataIndex: 'save_dvc_cnt/home_view_dvc_cnt', title: '总完成率' },
      { dataIndex: 'share_dvc_cnt', title: '分享量' },
      { dataIndex: 'share_dvc_cnt/make_button_click_dvc_cnt', title: '分享率(%)' },
      { dataIndex: 'make_fail_dvc_cnt', title: '模版制作失败量' },
      { dataIndex: 'make_fail_dvc_cnt/make_button_click_dvc_cnt', title: 'uv模板制作失败率(%)' },
      { dataIndex: 'make_fail_cnt/total_make_cnt', title: 'pv模板制作失败率(%)' },
      { dataIndex: 'home_click_cnt', title: '模板首页-点击/pv' },
      { dataIndex: 'template_make_dvc_cnt', title: '素材编辑/uv' },
      { dataIndex: 'save_cnt', title: '模版保存/pv' },
      { dataIndex: 'share_cnt', title: '模版分享/pv' },
      { dataIndex: 'home_click_cnt/home_click_dvc_cnt', title: '人均模版使用次数' },
      { dataIndex: 'save_cnt/save_dvc_cnt', title: '人均模版保存次数' },
      { dataIndex: 'share_cnt/share_dvc_cnt', title: '人均模版分享次数' },
      { dataIndex: 'total_make_cnt', title: '总制作量（pv）' },
    ],
  },
  10: [
    { dataIndex: 'tt_name', title: '模版名称' },
    { dataIndex: 'ttid', title: 'ttid' },
    { dataIndex: 'country', title: '国家' },
    { dataIndex: 'home_view_dvc_cnt', title: '封面曝光/uv' },
    { dataIndex: 'home_click_dvc_cnt', title: '封面点击/uv' },
    { dataIndex: 'home_click_dvc_cnt/home_view_dvc_cnt', title: '封面点击率' },
    { dataIndex: 'template_view_dvc_cnt', title: '详情曝光/uv' },
    { dataIndex: 'make_button_click_dvc_cnt', title: '素材使用/uv' },
    { dataIndex: 'make_button_click_dvc_cnt/template_view_dvc_cnt', title: '模版使用率' },
    { dataIndex: 'template_make_dvc_cnt', title: '素材编辑/uv' },
    { dataIndex: 'save_dvc_cnt', title: '素材保存/uv' },
    { dataIndex: 'save_dvc_cnt/template_make_dvc_cnt', title: '模板导出率（保存/编辑）' },
    { dataIndex: 'save_dvc_cnt/home_view_dvc_cnt', title: '总完成率' },
    { dataIndex: 'share_dvc_cnt', title: '素材分享/uv' },
    { dataIndex: 'share_dvc_cnt/save_dvc_cnt', title: '分享率(素材分享/保存）' },
    { dataIndex: 'make_button_click_cnt', title: '素材使用/pv' },
    { dataIndex: 'template_make_cnt', title: '素材编辑/pv' },
    { dataIndex: 'save_cnt', title: '素材保存/pv' },
    { dataIndex: 'share_cnt', title: '素材分享/pv' },
    { dataIndex: 'make_button_click_cnt/make_button_click_dvc_cnt', title: '人均素材使用次数' },
    { dataIndex: 'template_make_cnt/template_make_dvc_cnt', title: '人均素材编辑次数' },
    { dataIndex: 'save_cnt/save_dvc_cnt', title: '人均素材保存次数' },
    { dataIndex: 'share_cnt/share_dvc_cnt', title: '人均素材分享次数' },
    { dataIndex: 'total_make_dvc_cnt', title: '总制作量' },
    { dataIndex: 'make_fail_dvc_cnt', title: '模版制作失败量' },
    { dataIndex: 'make_fail_dvc_cnt/template_make_dvc_cnt', title: '模版制作失败率(%)' },
    { dataIndex: 'pay_dvc_cnt', title: '模版付费数' },
    { dataIndex: 'pay_dvc_cnt/template_view_dvc_cnt', title: '模版付费率(%)' },
    { dataIndex: 'week_buy_dvc_cnt', title: '周会员' },
    { dataIndex: 'month_buy_dvc_cnt', title: '月度会员购买' },
    { dataIndex: 'year_buy_dvc_cnt', title: '年度会员购买' },
    { dataIndex: 'forever_buy_dvc_cnt', title: '永久包购买' },
    { dataIndex: 'coin_60_dvc_cnt', title: '按60金币购买' },
    { dataIndex: 'coin_200_dvc_cnt', title: '按200金币购买' },
    { dataIndex: 'coin_1000_dvc_cnt', title: '按1000金币购买' },
  ],
  3: [
    { dataIndex: 'tt_name', title: '模版名称' },
    { dataIndex: 'ttid', title: 'ttid' },
    { dataIndex: 'home_view_dvc_cnt', title: '模版展示-首页展示' },
    { dataIndex: 'home_click_dvc_cnt', title: '模板首页-点击' },
    { dataIndex: 'home_click_dvc_cnt/home_view_dvc_cnt', title: '首页点击率(%)' },
    { dataIndex: 'template_view_dvc_cnt', title: '模版页展示量' },
    { dataIndex: 'template_make_dvc_cnt', title: '模版页制作量' },
    { dataIndex: 'template_make_dvc_cnt/template_view_dvc_cnt', title: '模版页制作率(%)' },
    { dataIndex: 'template_make_dvc_cnt/make_button_click_dvc_cnt', title: '模版导出率(%)' },
    { dataIndex: 'share_dvc_cnt', title: '视频分享量' },
    { dataIndex: 'share_dvc_cnt/template_make_dvc_cnt', title: '视频分享率(%)' },
    { dataIndex: 'template_make_dvc_cnt/home_view_dvc_cnt', title: '总完成率(%)' },
    { dataIndex: 'total_make_dvc_cnt', title: '总制作量' },
    { dataIndex: 'make_fail_dvc_cnt', title: '模版制作失败量' },
    { dataIndex: 'make_fail_dvc_cnt/template_make_dvc_cnt', title: '模版制作失败率(%)' },
    { dataIndex: 'week_buy_dvc_cnt', title: '周会员' },
    { dataIndex: 'month_buy_dvc_cnt', title: '月度会员购买' },
    { dataIndex: 'year_buy_dvc_cnt', title: '年度会员购买' },
    { dataIndex: 'forever_buy_dvc_cnt', title: '永久包购买' },
    { dataIndex: 'coin_60_dvc_cnt', title: '按60金币购买' },
    { dataIndex: 'coin_200_dvc_cnt', title: '按200金币购买' },
    { dataIndex: 'coin_1000_dvc_cnt', title: '按1000金币购买' },
  ],
};
