export const products = {
  install: {
    ds: 'bizdate',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'product',
      values: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
  sale: {
    ds: 'data_time',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'app_product',
      values: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
  cost: {
    ds: 'ds',
    country: 'country',
    platform: {
      field: 'platform',
      values: {
        1: '1',
        2: '2',
      },
    },
    product: {
      field: 'product_id',
      values: {
        2: '2',
        3: '3',
        6: '6',
        10: '10',
        15: '15',
        16: '16',
        33: '33',
        35: '35',
      },
      mapping: {
        2: 'viva',
        3: 'sp',
        6: 'vid',
        10: 'tempo',
        15: 'vivacut',
        16: 'vivamini',
        33: 'picsfox',
        35: 'facee',
      },
    },
  },
};

export const productMapping = {
  2: 'viva',
  3: 'sp',
  6: 'vid',
  10: 'tempo',
  15: 'vivacut',
  16: 'vivamini',
  33: 'picsfox',
  35: 'facee',
  18: 'VMix',
  36: 'Glitch',
  44: '小影印度马甲包',
  43: 'GoCut',
  42: 'mast',
  41: 'StoryBuff',
  39: 'Veffecto',
};

export const estimateLTVColumns = [
  {
    title: '日期',
    dataIndex: 'day',
    key: 'day',
    align: 'center',
    render: text => text,
  },
  {
    title: '新增',
    dataIndex: 'reg_num',
    key: 'reg_num',
    align: 'center',
    render: text => text,
  },
  {
    title: '7天后LTV',
    dataIndex: 'ltv_7',
    key: 'ltv_7',
    align: 'center',
    render: text => text,
  },
  {
    title: '7天留存率',
    dataIndex: 'stay_rate_7',
    key: 'stay_rate_7',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '14天后LTV',
    dataIndex: 'ltv_14',
    key: 'ltv_14',
    align: 'center',
    render: text => text,
  },
  {
    title: '14天留存率',
    dataIndex: 'stay_rate_14',
    key: 'stay_rate_14',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '28天后LTV',
    dataIndex: 'ltv_28',
    key: 'ltv_28',
    align: 'center',
    render: text => text,
  },
  {
    title: '28天留存率',
    dataIndex: 'stay_rate_28',
    key: 'stay_rate_28',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '60天后LTV',
    dataIndex: 'ltv_60',
    key: 'ltv_60',
    align: 'center',
    render: text => text,
  },
  {
    title: '60天留存率',
    dataIndex: 'stay_rate_60',
    key: 'stay_rate_60',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
];

export const realLTVColumns = [
  {
    title: '日期',
    dataIndex: 'day',
    key: 'day',
    align: 'center',
    render: text => text,
  },
  {
    title: '新增',
    dataIndex: 'reg_num',
    key: 'reg_num',
    align: 'center',
    render: text => text,
  },

  {
    title: '1天后LTV',
    dataIndex: 'ltv_1',
    key: 'ltv_1',
    align: 'center',
    render: text => text,
  },
  {
    title: '1天留存率',
    dataIndex: 'stay_rate_1',
    key: 'stay_rate_1',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '3天后LTV',
    dataIndex: 'ltv_3',
    key: 'ltv_3',
    align: 'center',
    render: text => text,
  },
  {
    title: '3天留存率',
    dataIndex: 'stay_rate_3',
    key: 'stay_rate_3',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '7天后LTV',
    dataIndex: 'ltv_7',
    key: 'ltv_7',
    align: 'center',
    render: text => text,
  },
  {
    title: '7天留存率',
    dataIndex: 'stay_rate_7',
    key: 'stay_rate_7',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '14天后LTV',
    dataIndex: 'ltv_14',
    key: 'ltv_14',
    align: 'center',
    render: text => text,
  },
  {
    title: '14天留存率',
    dataIndex: 'stay_rate_14',
    key: 'stay_rate_14',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '28天后LTV',
    dataIndex: 'ltv_28',
    key: 'ltv_28',
    align: 'center',
    render: text => text,
  },
  {
    title: '28天留存率',
    dataIndex: 'stay_rate_28',
    key: 'stay_rate_28',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
  {
    title: '60天后LTV',
    dataIndex: 'ltv_60',
    key: 'ltv_60',
    align: 'center',
    render: text => text,
  },
  {
    title: '60天留存率',
    dataIndex: 'stay_rate_60',
    key: 'stay_rate_60',
    align: 'center',
    render: text => `${text ? `${text}%` : ''}`,
  },
];
